In [ ]:
import pandas as pd

# Load the uploaded dataset to inspect its structure and contents
file_path = '/content/food_dataset.csv'
dataset = pd.read_csv(file_path)

# Display the first few rows and summary information about the dataset
dataset_info = dataset.info()
dataset_head = dataset.head()

dataset_info, dataset_head


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Food_Item           50000 non-null  object 
 1   Category            50000 non-null  object 
 2   Sugar_Content (g)   50000 non-null  float64
 3   Calories (kcal)     50000 non-null  float64
 4   Protein (g)         50000 non-null  float64
 5   Fiber (g)           50000 non-null  float64
 6   Carbohydrates (g)   50000 non-null  float64
 7   Glycemic_Index      50000 non-null  int64  
 8   Ripeness            50000 non-null  object 
 9   Size                50000 non-null  object 
 10  Average_Weight (g)  50000 non-null  float64
 11  Fruit               50000 non-null  bool   
dtypes: bool(1), float64(6), int64(1), object(4)
memory usage: 4.2+ MB


(None,
      Food_Item   Category  Sugar_Content (g)  Calories (kcal)  Protein (g)  \
 0    Jackfruit      Fruit               10.8             99.9          0.6   
 1       Potato  Vegetable                4.1             57.2          3.9   
 2       Banana      Fruit               16.4             77.5          1.9   
 3  Pomegranate      Fruit               10.8             32.1          0.6   
 4        Onion  Vegetable                2.4             46.8          3.1   
 
    Fiber (g)  Carbohydrates (g)  Glycemic_Index Ripeness    Size  \
 0        3.2               16.0              47   Unripe  Medium   
 1        6.1               11.2              32     Ripe  Medium   
 2        1.6                6.3              68     Ripe  Medium   
 3        2.7               17.0              64   Unripe   Small   
 4        2.9                6.6              22   Unripe  Medium   
 
    Average_Weight (g)  Fruit  
 0               473.8   True  
 1               594.3  False  
 2   

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Encoding categorical variables
label_encoders = {}
categorical_columns = ['Ripeness', 'Size', 'Category']
for col in categorical_columns:
    le = LabelEncoder()
    dataset[col] = le.fit_transform(dataset[col])
    label_encoders[col] = le

# Normalizing numerical columns
scaler = StandardScaler()
numerical_columns = [
    'Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)',
    'Fiber (g)', 'Carbohydrates (g)', 'Glycemic_Index', 'Average_Weight (g)'
]
dataset[numerical_columns] = scaler.fit_transform(dataset[numerical_columns])

# Display the first few rows after preprocessing
dataset.head()


Food_Item  Category  Sugar_Content (g)  Calories (kcal)  Protein (g)  \
0    Jackfruit         0           0.813479         2.223230    -1.535837   
1       Potato         1          -0.382716         0.104333     1.326744   
2       Banana         0           1.813284         1.111677    -0.408154   
3  Pomegranate         0           0.813479        -1.141201    -1.535837   
4        Onion         1          -0.686229        -0.411745     0.632785   

   Fiber (g)  Carbohydrates (g)  Glycemic_Index  Ripeness  Size  \
0  -0.226783           0.719044       -0.381182         2     1   
1   1.291141          -0.136494       -1.087568         1     1   
2  -1.064259          -1.009856        0.607757         1     1   
3  -0.488494           0.897281        0.419388         2     2   
4  -0.383810          -0.956385       -1.558491         2     1   

   Average_Weight (g)  Fruit  
0           -0.156868   True  
1            0.145707  False  
2           -0.190264   True  
3           -0.596292   True  
4           -0.864717  False

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

# Define features (X) and target (y)
X = dataset.drop(columns=['Food_Item', 'Fruit'])  # Exclude identifiers and target column
y = dataset['Fruit']  # Target is whether the item is a fruit

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Define a RandomForestClassifier and GridSearchCV for hyperparameter tuning
rf_model = RandomForestClassifier(random_state=42)
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
}

grid_search = GridSearchCV(rf_model, param_grid, cv=3, scoring='accuracy', verbose=1)
grid_search.fit(X_train, y_train)

# Get the best model and evaluate on the test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

grid_search.best_params_, accuracy


Fitting 3 folds for each of 24 candidates, totalling 72 fits


({'max_depth': 10,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'n_estimators': 100},
 1.0)

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the dataset
file_path = 'food_dataset.csv'  # Replace with your dataset file path
dataset = pd.read_csv(file_path)

# Step 1: Preprocess the dataset
# Encode categorical variables
label_encoders = {}
categorical_columns = ['Ripeness', 'Size', 'Category']
for col in categorical_columns:
    le = LabelEncoder()
    dataset[col] = le.fit_transform(dataset[col])
    label_encoders[col] = le

# Normalize numerical features
scaler = StandardScaler()
numerical_columns = [
    'Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)',
    'Fiber (g)', 'Carbohydrates (g)', 'Glycemic_Index', 'Average_Weight (g)'
]
dataset[numerical_columns] = scaler.fit_transform(dataset[numerical_columns])

# Define features (X) and target (y)
X = dataset.drop(columns=['Food_Item', 'Fruit'])  # Drop identifiers and target
y = dataset['Fruit']  # Target is whether the item is a fruit

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Step 2: Train a Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Step 3: Define recommendation logic
def recommend_replacements(user_sugar_level, selected_items):
    # Filter the dataset for the user's selected fruits/vegetables
    selected_data = dataset[dataset['Food_Item'].isin(selected_items)]
    total_sugar = selected_data['Sugar_Content (g)'].sum()

    if total_sugar <= user_sugar_level:
        return f"Your selected items are within your sugar limit of {user_sugar_level}g. No replacements needed."

    # Find replacements by selecting items with lower sugar content
    replacements = dataset[~dataset['Food_Item'].isin(selected_items)]  # Exclude selected items
    replacements = replacements.sort_values(by='Sugar_Content (g)')  # Sort by sugar content

    # Suggest replacements that match nutritional levels (Calories, Protein, Fiber, etc.)
    suggestions = []
    for _, item in selected_data.iterrows():
        for _, replacement in replacements.iterrows():
            # Match based on nutritional similarity (simple threshold comparison for now)
            if abs(item['Calories (kcal)'] - replacement['Calories (kcal)']) <= 0.2 and \
               abs(item['Protein (g)'] - replacement['Protein (g)']) <= 0.2 and \
               replacement['Sugar_Content (g)'] < item['Sugar_Content (g)']:
                suggestions.append((item['Food_Item'], replacement['Food_Item']))
                break

    return suggestions if suggestions else "No suitable replacements found."

# Step 4: User interaction
print("\n--- Sugar Intake Recommendation System ---")
user_sugar_level = float(input("Enter your maximum sugar intake level (g): "))
selected_items = input("Enter the fruits/vegetables you consume (comma-separated): ").split(',')

# Get recommendations
recommendations = recommend_replacements(user_sugar_level, [item.strip() for item in selected_items])
print("\nRecommendations:")
if isinstance(recommendations, str):
    print(recommendations)
else:
    for original, replacement in recommendations:
        print(f"Replace '{original}' with '{replacement}'.")


Streaming output truncated to the last 5000 lines.
Replace 'Mango' with 'Pear'.
Replace 'Orange' with 'Garlic'.
Replace 'Orange' with 'Brinjal'.
Replace 'Orange' with 'Custard Apple'.
Replace 'Orange' with 'Fenugreek'.
Replace 'Grapes' with 'Lychee'.
Replace 'Grapes' with 'Chayote'.
Replace 'Grapes' with 'Pear'.
Replace 'Papaya' with 'Sweet Corn'.
Replace 'Mango' with 'Colocasia'.
Replace 'Grapes' with 'Chayote'.
Replace 'Orange' with 'Lychee'.
Replace 'Guava' with 'Carrot'.
Replace 'Orange' with 'Custard Apple'.
Replace 'Orange' with 'Tamarind'.
Replace 'Mango' with 'Pear'.
Replace 'Guava' with 'Banana'.
Replace 'Orange' with 'Dragon Fruit'.
Replace 'Mango' with 'Lychee'.
Replace 'Papaya' with 'Tamarind'.
Replace 'Grapes' with 'Ginger'.
Replace 'Grapes' with 'Sapodilla'.
Replace 'Orange' with 'Plum'.
Replace 'Grapes' with 'Fig'.
Replace 'Grapes' with 'Beetroot'.
Replace 'Grapes' with 'Colocasia'.
Replace 'Mango' with 'Colocasia'.
Replace 'Guava' with 'Spinach'.
Replace 'Guava' with 'P

Model Accuracy: 1.00

--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 12
Enter the fruits/vegetables you consume (comma-separated): Banana

Total sugar content of selected items: 702.37g

Recommendations:
Replaced high-sugar items with: Guava, Pineapple, Orange

Nutritional Values:
Original Nutrition:
Sugar_Content (g)     702.366503
Calories (kcal)       424.697199
Protein (g)          -527.025215
Fiber (g)            -480.869980
Carbohydrates (g)     480.727634
Glycemic_Index        680.032243
Average_Weight (g)   -657.497006
dtype: float64

Replaced Nutrition:
Sugar_Content (g)     -78.050760
Calories (kcal)       234.864872
Protein (g)          -262.940020
Fiber (g)            -245.398147
Carbohydrates (g)     217.130569
Glycemic_Index        356.837849
Average_Weight (g)   -335.968928
dtype: float64


In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the dataset
file_path = 'food_dataset.csv'  # Replace with your dataset file path
dataset = pd.read_csv(file_path)

# Step 1: Preprocess the dataset
# Save original numerical values for reporting purposes
original_numerical = dataset[['Food_Item', 'Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)', 'Fiber (g)']].copy()

# Encode categorical variables
label_encoders = {}
categorical_columns = ['Ripeness', 'Size', 'Category']
for col in categorical_columns:
    le = LabelEncoder()
    dataset[col] = le.fit_transform(dataset[col])
    label_encoders[col] = le

# Normalize numerical features
scaler = StandardScaler()
numerical_columns = [
    'Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)',
    'Fiber (g)', 'Carbohydrates (g)', 'Glycemic_Index', 'Average_Weight (g)'
]
dataset[numerical_columns] = scaler.fit_transform(dataset[numerical_columns])

# Define features (X) and target (y)
X = dataset.drop(columns=['Food_Item', 'Fruit'])  # Drop identifiers and target
y = dataset['Fruit']  # Target is whether the item is a fruit

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Step 2: Train a Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)

# Evaluate the model
y_pred = rf_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Step 3: Define recommendation logic
def recommend_replacements(user_sugar_level, selected_items):
    # Clean user input to avoid mismatches
    selected_items = [item.strip().capitalize() for item in selected_items]

    # Filter the original dataset for the user's selected fruits/vegetables
    selected_data = original_numerical[original_numerical['Food_Item'].isin(selected_items)]
    if selected_data.empty:
        print("Error: None of the entered items match the dataset. Check spelling or case sensitivity.")
        return None

    # Calculate total sugar content from unnormalized data
    total_sugar = selected_data['Sugar_Content (g)'].sum()

    print(f"\nTotal Sugar Content in Selected Items: {total_sugar:.2f}g")

    if total_sugar <= user_sugar_level:
        print(f"Your selected items are within your sugar limit of {user_sugar_level}g. No replacements needed.")
        print("\nNutritional Value of Selected Items:")
        print(selected_data[['Food_Item', 'Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)', 'Fiber (g)']])
        return None

    # Find replacements by selecting items with lower sugar content
    replacements = original_numerical[~original_numerical['Food_Item'].isin(selected_items)]  # Exclude selected items
    replacements = replacements.sort_values(by='Sugar_Content (g)')  # Sort by sugar content

    suggestions = []
    for _, item in selected_data.iterrows():
        for _, replacement in replacements.iterrows():
            if abs(item['Calories (kcal)'] - replacement['Calories (kcal)']) <= 20 and \
               abs(item['Protein (g)'] - replacement['Protein (g)']) <= 2 and \
               replacement['Sugar_Content (g)'] < item['Sugar_Content (g)']:
                suggestions.append((item['Food_Item'], replacement['Food_Item']))
                break

    # Limit suggestions to 3 items
    suggestions = suggestions[:3]

    print("\nNutritional Value of Replacements:")
    for original, replacement in suggestions:
        original_nutrition = selected_data[selected_data['Food_Item'] == original]
        replacement_nutrition = original_numerical[original_numerical['Food_Item'] == replacement]
        print(f"Replace '{original}' with '{replacement}':")
        print("Original:", original_nutrition[['Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)', 'Fiber (g)']].values)
        print("Replacement:", replacement_nutrition[['Sugar_Content (g)', 'Calories (kcal)', 'Protein (g)', 'Fiber (g)']].values)

    return suggestions

# Step 4: User interaction
print("\n--- Sugar Intake Recommendation System ---")
user_sugar_level = float(input("Enter your maximum sugar intake level (g): "))
selected_items = input("Enter the fruits/vegetables you consume (comma-separated): ").split(',')

# Get recommendations
recommendations = recommend_replacements(user_sugar_level, [item.strip() for item in selected_items])
if recommendations:
    print("\nRecommendations:")
    for original, replacement in recommendations:
        print(f"Replace '{original}' with '{replacement}'.")


Model Accuracy: 1.00

--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 13
Enter the fruits/vegetables you consume (comma-separated): Banana

Total Sugar Content in Selected Items: 10127.70g

Nutritional Value of Replacements:
Replace 'Banana' with 'Mango':
Original: [[16.4 77.5  1.9  1.6]
 [18.  46.3  1.7  2.2]
 [13.5 38.   1.1  3.9]
 ...
 [ 3.6 37.   1.6  4.2]
 [20.  72.   1.3  2.5]
 [ 4.9 85.7  1.3  3.3]]
Replacement: [[ 2.4 50.1  1.2  4.8]
 [ 8.1 69.4  2.6  0.9]
 [ 4.7 88.6  1.9  3. ]
 ...
 [ 6.5 45.2  1.6  3.3]
 [14.6 61.3  2.3  3.5]
 [17.3 75.4  3.   1.5]]
Replace 'Banana' with 'Spinach':
Original: [[16.4 77.5  1.9  1.6]
 [18.  46.3  1.7  2.2]
 [13.5 38.   1.1  3.9]
 ...
 [ 3.6 37.   1.6  4.2]
 [20.  72.   1.3  2.5]
 [ 4.9 85.7  1.3  3.3]]
Replacement: [[ 4.9 46.3  3.6  5.8]
 [ 1.5 62.5  2.   4.9]
 [ 2.1 70.   3.2  3.8]
 ...
 [ 4.3 66.7  4.5  6.3]
 [ 4.3 25.7  4.3  4.2]
 [ 1.3 31.2  1.6  1.9]]
Replace 'Banana' with 'Spinach':
Original: [[16.4 7

In [ ]:
#the code works, solvves the issue of sugar_pediction
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
file_path = 'food_dataset.csv'
dataset = pd.read_csv(file_path)

# Preprocessing
features = ['Calories (kcal)', 'Protein (g)', 'Fiber (g)', 'Sugar_Content (g)']
X = dataset[features]
y = dataset['Food_Item']

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Adjusted recommendation function
def recommend_replacements(user_sugar_limit, selected_items, sweetness_inputs):
    selected_items = [item.strip().capitalize() for item in selected_items]
    selected_data = []

    # Choose only one entry per fruit based on sweetness input
    for fruit, sweetness in zip(selected_items, sweetness_inputs):
        fruit_data = dataset[dataset['Food_Item'] == fruit]
        if not fruit_data.empty:
            # Adjust the sugar content based on sweetness input
            sweetness_map = {
                'little': 0.8,
                'moderate': 1.0,
                'too much': 1.2
            }
            adjustment_factor = sweetness_map.get(sweetness.lower(), 1.0)
            adjusted_sugar_content = fruit_data['Sugar_Content (g)'].values[0] * adjustment_factor

            fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
            selected_data.append(fruit_data.iloc[0])

    if not selected_data:
        return "Error: None of the entered items match the dataset. Please check your input."

    # Convert to DataFrame
    selected_data = pd.DataFrame(selected_data)

    # Calculate total sugar content
    total_sugar = selected_data['Adjusted_Sugar_Content'].sum()
    print(f"\nTotal Sugar Content in Selected Items: {total_sugar:.2f}g")

    if total_sugar <= user_sugar_limit:
        print(f"Your selected items are within your sugar limit of {user_sugar_limit}g. No replacements needed.")
        return None

    print(f"Your selected items exceed your sugar limit of {user_sugar_limit}g. Suggesting replacements...\n")
    recommendations = []

    for _, item in selected_data.iterrows():
        item_features = item[features].values.reshape(1, -1)
        # Predict similar items
        similar_items = rf_model.predict(X_scaled)

        # Filter lower-sugar replacements
        low_sugar_options = dataset[
            (dataset['Sugar_Content (g)'] < item['Adjusted_Sugar_Content']) &
            (dataset['Category'] == item['Category'])
        ].sort_values(by='Sugar_Content (g)').head(1)

        if not low_sugar_options.empty:
            replacement = low_sugar_options.iloc[0]['Food_Item']
            recommendations.append((item['Food_Item'], replacement))
        else:
            recommendations.append((item['Food_Item'], "No suitable replacement found"))

    return recommendations

# User Interaction
print("\n--- Sugar Intake Recommendation System ---")
user_sugar_level = float(input("Enter your maximum sugar intake level (g): "))
selected_items = input("Enter the fruits/vegetables you consume (comma-separated): ").split(',')
sweetness_inputs = input("Rate the sweetness of each fruit (little, moderate, too much): ").split(',')

# Get recommendations
recommendations = recommend_replacements(user_sugar_level, selected_items, sweetness_inputs)

if recommendations:
    print("\nRecommendations:")
    for original, replacement in recommendations:
        print(f"Replace '{original}' with '{replacement}'.")



--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 18
Enter the fruits/vegetables you consume (comma-separated): Banana, Peach
Rate the sweetness of each fruit (little, moderate, too much): little,little


<ipython-input-22-71c22ca64312>:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
<ipython-input-22-71c22ca64312>:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content



Total Sugar Content in Selected Items: 28.48g
Your selected items exceed your sugar limit of 18.0g. Suggesting replacements...


Recommendations:
Replace 'Banana' with 'Sapodilla'.
Replace 'Peach' with 'Peach'.


In [ ]:
#This code works perfeclty and accurely
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
file_path = '/content/drive/MyDrive/dataset/food_dataset.csv'  # Make sure this file exists in your environment
dataset = pd.read_csv(file_path)

# Preprocessing
features = ['Calories (kcal)', 'Protein (g)', 'Fiber (g)', 'Sugar_Content (g)']
X = dataset[features]
y = dataset['Food_Item']

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train/Test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Enhanced recommendation function
def recommend_replacements(user_sugar_limit, selected_items, sweetness_inputs):
    selected_items = [item.strip().capitalize() for item in selected_items]
    selected_data = []

    # Choose only one entry per fruit based on sweetness input
    for fruit, sweetness in zip(selected_items, sweetness_inputs):
        fruit_data = dataset[dataset['Food_Item'] == fruit]
        if not fruit_data.empty:
            # Adjust the sugar content based on sweetness input
            sweetness_map = {
                'little': 0.8,
                'moderate': 1.0,
                'too much': 1.2
            }
            adjustment_factor = sweetness_map.get(sweetness.lower(), 1.0)
            adjusted_sugar_content = fruit_data['Sugar_Content (g)'].values[0] * adjustment_factor

            fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
            selected_data.append(fruit_data.iloc[0])

    if not selected_data:
        return "Error: None of the entered items match the dataset. Please check your input."

    # Convert to DataFrame
    selected_data = pd.DataFrame(selected_data)

    # Calculate total sugar content
    total_sugar = selected_data['Adjusted_Sugar_Content'].sum()
    print(f"\nTotal Sugar Content in Selected Items: {total_sugar:.2f}g")

    if total_sugar <= user_sugar_limit:
        print(f"Your selected items are within your sugar limit of {user_sugar_limit}g. No replacements needed.")
        return None

    print(f"Your selected items exceed your sugar limit of {user_sugar_limit}g. Suggesting replacements...\n")

    # Start replacing items one by one
    replacements = []
    current_sugar = total_sugar

    # Iterate over each selected item and suggest a replacement
    for _, item in selected_data.iterrows():
        if current_sugar <= user_sugar_limit:
            break  # If the sugar content is already within the limit, stop replacing

        # Find a lower-sugar replacement
        lower_sugar_options = dataset[
            (dataset['Sugar_Content (g)'] < item['Adjusted_Sugar_Content']) &
            (dataset['Category'] == item['Category'])
        ].sort_values(by='Sugar_Content (g)').head(3)  # Take top 3 lower-sugar options

        # If there are replacements available
        if not lower_sugar_options.empty:
            # Pick the lowest-sugar replacement
            replacement = lower_sugar_options.iloc[0]
            replacements.append((item['Food_Item'], replacement['Food_Item']))
            current_sugar -= (item['Adjusted_Sugar_Content'] - replacement['Sugar_Content (g)'])
        else:
            replacements.append((item['Food_Item'], "No suitable replacement found"))

    # If after all replacements the total sugar is still too high
    if current_sugar > user_sugar_limit:
        print("Even after replacing some items, the total sugar content still exceeds the limit.")
    return replacements

# User Interaction
print("\n--- Sugar Intake Recommendation System ---")
user_sugar_level = float(input("Enter your maximum sugar intake level (g): "))
selected_items = input("Enter the fruits/vegetables you consume (comma-separated): ").split(',')
sweetness_inputs = input("Rate the sweetness of each fruit (little, moderate, too much): ").split(',')

# Get recommendations
recommendations = recommend_replacements(user_sugar_level, selected_items, sweetness_inputs)

if recommendations:
    print("\nRecommendations:")
    for original, replacement in recommendations:
        print(f"Replace '{original}' with '{replacement}'.")



--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 8
Enter the fruits/vegetables you consume (comma-separated): Pineapple,Custard Apple
Rate the sweetness of each fruit (little, moderate, too much): little,little

Total Sugar Content in Selected Items: 1.52g
Your selected items are within your sugar limit of 8.0g. No replacements needed.


<ipython-input-3-4c714105cfee>:45: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content




```
--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 8
Enter the fruits/vegetables you consume (comma-separated): Apple, Banana
Rate the sweetness of each fruit (little, moderate, too much): little,moderate

Total Sugar Content in Selected Items: 24.56g
Your selected items exceed your sugar limit of 8.0g. Suggesting replacements...


Recommendations:
Replace 'Apple' with 'Pineapple'.
Replace 'Banana' with 'Custard Apple'.
<ipython-input-2-4c714105cfee>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
<ipython-input-2-4c714105cfee>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
```





```
--- Sugar Intake Recommendation System ---
Enter your maximum sugar intake level (g): 18
Enter the fruits/vegetables you consume (comma-separated): Apple, Banana
Rate the sweetness of each fruit (little, moderate, too much): little, moderate

Total Sugar Content in Selected Items: 24.56g
Your selected items exceed your sugar limit of 18.0g. Suggesting replacements...


Recommendations:
Replace 'Apple' with 'Pineapple'.
<ipython-input-1-4a377cd51b60>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
<ipython-input-1-4a377cd51b60>:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fruit_data['Adjusted_Sugar_Content'] = adjusted_sugar_content
```

